name: Sealer-Test

on:
  pull_request:
    types: [ labeled ]
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'vendor/**'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'apply-test' }}
    env:
      GO111MODULE: on
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: src/github.com/alibaba/sealer

      - name: Install sealer
        shell: bash
        run: |
          source hack/build.sh
          export SEALER_DIR=$THIS_PLATFORM_BIN/sealer/linux_amd64
          echo "$SEALER_DIR" >> $GITHUB_PATH
        working-directory: src/github.com/alibaba/sealer

      - name: Install ginkgo
          shell: bash
          run: |
            go get github.com/onsi/ginkgo/ginkgo
            export SEALER_DIR=$GOPATH/bin
            echo "$SEALER_DIR" >> $GITHUB_PATH
          working-directory: src/github.com/alibaba/sealer


      - name: Run e2e test
        shell: bash
        working-directory: src/github.com/alibaba/sealer
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
          ACCESSKEYSECRET: ${{ secrets.ACCESSKEYSECRET }}
          RegionID: ${{ secrets.RegionID }}
        run: ginkgo  -v --focus="sealer apply" test

